### ISSUE TITLE
💄 Apply Patternfly to the product list page 

### ISSUE THREAD

**Issue by didierofrivia** [3scale/k8sapp-initiative#20]
Depends on https://github.com/3scale/k8sapp-initiative/pull/16 and https://github.com/3scale/k8sapp-initiative/pull/19

What is now a simple table displaying a Product (CR) list should be render following the Patternfly directives.

This:

<img width="664" alt="Screenshot 2020-11-27 at 16 05 55" src="https://user-images.githubusercontent.com/4183971/100598309-24475200-3331-11eb-8ae0-d8e5f1490e69.png">

Should look like this:

<img width="1283" alt="Screenshot 2020-11-18 at 12 36 01" src="https://user-images.githubusercontent.com/4183971/100598358-31fcd780-3331-11eb-8082-26253f5dc1a9.png">

Just the title and the table, we don't need the buttons, context selector, etc...

**Comment by damianpm** [comment]
Closed by https://github.com/3scale/k8sapp-initiative/pull/22
