### ISSUE TITLE
Create more CRs for products.

### ISSUE THREAD

**Issue by Martouta** [3scale/k8sapp-initiative#6]
Right now we have only 1 and with only 1 attribute. We need more for the list.

Perhaps even add an [OpenAPI v3 validation](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#advanced-features-and-flexibility) in the CRD.

**Comment by didierofrivia** [comment]
This was closed by https://github.com/3scale/k8sapp-initiative/pull/18
